### PR TITLE
ReadMe & Wallpapers

### PR DESCRIPTION
**Pull request by rafay99-epic**
# Changes:
So here are all of the changes that I have made.

## Read Me:
Updating the readme file. In the readme file, I have added the purpose of this repository, an introduction, a code contribution, and the names of the authors.

## Wallpapers:
In this patch, I have also added some more wallpapers. I hope you will like them.

### CODE REVIEW

**Review by atraxsrc — COMMENTED** [review]
There are some spelling mistakes

**Comment by rafay99-epic** [comment]
> There are some spelling mistakes

Oh yeah, thanks for the correction. I will be careful.

**Review by atraxsrc — COMMENTED** [review]
Add

**Review by atraxsrc — COMMENTED** [review]
done

**Comment by rafay99-epic** [comment]
Thanks.

**Pull request merged**
